services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: qlpt-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: qlpt_root_password
      MYSQL_DATABASE: quan_ly_phong_tro
      MYSQL_USER: qlpt_user
      MYSQL_PASSWORD: qlpt_password
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/quan_ly_phong_tro.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - qlpt-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Tomcat with manual WAR deployment
  tomcat:
    image: tomcat:9.0-jdk17
    container_name: qlpt-tomcat
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8087:8080"
    environment:
      CATALINA_OPTS: "-Xms512m -Xmx1024m"
      JAVA_OPTS: "-Djava.awt.headless=true -Dfile.encoding=UTF-8 -Duser.timezone=Asia/Ho_Chi_Minh"
    volumes:
      - ./target/QuanLyPhongTro.war:/usr/local/tomcat/webapps/ROOT.war
      - tomcat_logs:/usr/local/tomcat/logs
    networks:
      - qlpt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: qlpt-phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: qlpt_user
      PMA_PASSWORD: qlpt_password
      MYSQL_ROOT_PASSWORD: qlpt_root_password
    networks:
      - qlpt-network

volumes:
  mysql_data:
    driver: local
  tomcat_logs:
    driver: local

networks:
  qlpt-network:
    driver: bridge